name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ashwin1121/backend
      TAG: v${{ github.run_number }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Skip tests (no test script defined)
        run: echo "Skipping tests"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      # Optional: Trigger deploy via GKE or another mechanism
      # - name: Deploy to GKE
      #   run: |
      #     gcloud container clusters get-credentials ...
      #     kubectl set image deployment/backend backend=$IMAGE_NAME:$TAG
